defmodule Flatbuffer.FlatcInteropTest do
  use ExUnit.Case, async: false

  @moduletag :flatc

  alias Flatbuffer.Schema

  @fixtures Path.expand("../fixtures/flatc", __DIR__)
  @schema_file Path.join(@fixtures, "interop.fbs")
  @json_file Path.join(@fixtures, "interop.json")
  @checker_file Path.join(@fixtures, "read_interop.cc")

  @expected %{
    active: true,
    count: 4_000_000_000,
    score: 1.25,
    mood: :CURIOUS,
    position: %{x: 1.5, y: -2.25, z: 3.75},
    name: "interoperable",
    values: [-2, 0, 3],
    child: %{id: 7, label: "nested"}
  }

  setup_all do
    flatc = System.find_executable("flatc") || flunk("flatc is required for this test")
    cxx = System.find_executable("c++") || flunk("c++ is required for this test")

    directory =
      Path.join(System.tmp_dir!(), "eflatbuffers-flatc-#{System.unique_integer([:positive])}")

    File.mkdir_p!(directory)
    on_exit(fn -> File.rm_rf!(directory) end)

    include_directory = flatc |> Path.dirname() |> Path.dirname() |> Path.join("include")

    run!(flatc, ["--cpp", "-o", directory, @schema_file])

    checker = Path.join(directory, "read_interop")

    run!(cxx, [
      "-std=c++17",
      "-I#{include_directory}",
      "-I#{directory}",
      @checker_file,
      "-o",
      checker
    ])

    {:ok, flatc_executable: flatc, checker: checker, directory: directory}
  end

  test "decodes a buffer generated by flatc", %{
    flatc_executable: flatc,
    directory: directory
  } do
    run!(flatc, ["--binary", "-o", directory, @schema_file, @json_file])

    {:ok, schema} = Schema.from_file(@schema_file)
    buffer = File.read!(Path.join(directory, "interop.bin"))

    assert @expected == Flatbuffer.read!(buffer, schema)
  end

  test "generated C++ verifies and reads a buffer encoded by Flatbuffer", %{
    checker: checker,
    directory: directory
  } do
    {:ok, schema} = Schema.from_file(@schema_file)
    buffer_file = Path.join(directory, "eflatbuffers.bin")

    File.write!(buffer_file, Flatbuffer.to_binary(@expected, schema))

    run!(checker, [buffer_file])
  end

  defp run!(executable, arguments) do
    {output, status} = System.cmd(executable, arguments, stderr_to_stdout: true)

    assert status == 0,
           "command failed (#{status}): #{executable} #{Enum.join(arguments, " ")}\n#{output}"

    output
  end
end
